### PR TITLE
issue-11 delete to respect optional nonStandardPath similar to get and create

### PR DESCRIPTION
**Pull request by khalidKhaliqi**

### CODE REVIEW

**Comment by khalidKhaliqi** [comment]
@ksnyde please review this PR and let me know if you have any questions.

**Comment by Aqua-4** [comment]
These changes fixed the delete function.

**Comment by ksnyde** [comment]
thanks @khalidKhaliqi and sorry for the very delayed response. I'll merge this in now.

**Comment by yankeeinlondon** [comment]
released as `0.4.0`

**Pull request merged**
